dist: xenial
language: python
sudo: required
python:
    - "2.6"
    - "2.7"
env: PGVERSION=9.6
addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-server-dev-9.6

install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
